package Method.Client;

import net.minecraftforge.fml.common.*;
import Method.Client.utils.*;
import Method.Client.module.Onscreen.*;
import Method.Client.utils.Screens.Custom.Packet.*;
import Method.Client.utils.Screens.Custom.Xray.*;
import Method.Client.utils.Screens.Custom.Search.*;
import Method.Client.utils.Screens.Custom.Esp.*;
import Method.Client.clickgui.*;
import Method.Client.utils.Factory.*;
import Method.Client.utils.Creativetabs.*;
import net.minecraft.client.*;
import Method.Client.utils.font.*;
import net.minecraftforge.common.*;
import Method.Client.module.*;
import Method.Client.utils.Screens.*;
import net.minecraftforge.fml.common.event.*;
import Method.Client.utils.system.*;
import Method.Client.managers.*;
import org.lwjgl.opengl.*;
import Method.Client.utils.proxy.*;
import org.apache.logging.log4j.*;

@Mod(modid = "futurex", name = "FutureX", version = "0.0.1", acceptableRemoteVersions = "*", guiFactory = "Method.Client.utils.Factory.MethodGuiFactory")
public class Main
{
    @SidedProxy(clientSide = "Method.Client.utils.proxy.ClientProxy", serverSide = "Method.Client.utils.proxy.ServerProxy")
    public static IProxy proxy;
    public static final String MODID = "futurex";
    public static final String NAME = "FutureX";
    public static final String MODCREDITS = "FutureX";
    public static final String VERSION = "0.0.1";
    public static final String MCVERSION = "1.12.2";
    public static final String MODURL = "https://github.com/FutureXClient/FutureX";
    public static final String MODLOGO = "assets/futurex/futurex.png";
    public static final Logger LOGGER;
    @Mod.Instance
    public static Main instance;
    public static SettingsManager setmgr;
    public static EventsHandler Evtmgr;
    public static CustomEventsHandler Cevtmgr;
    public static OnscreenGUI OnscreenGUI;
    public static AntiPacketGui AntiPacketgui;
    public static XrayGui Xray;
    public static SearchGui Search;
    public static EspGui GuiEsp;
    public static ClickGui ClickGui;
    public static MethodConfig config;
    
    @Mod.EventHandler
    public void preInit(final FMLPreInitializationEvent event) {
        Main.LOGGER.info("Initializing FutureX Version 0.0.1");
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "FutureX";
        event.getModMetadata().authorList.clear();
        event.getModMetadata().credits = "FutureX";
        event.getModMetadata().url = "https://github.com/FutureXClient/FutureX";
        event.getModMetadata().logoFile = "assets/futurex/futurex.png";
        new CreativeTabBlocks();
        new CreativeTabItems();
        new CreativeTabBreak();
        new CreativeTabArmor();
        new CreativeTabFun();
        (Main.config = new MethodConfig()).preInit(event);
        Minecraft.func_71410_x().field_71474_y.field_74335_Z = 2;
        CFont.setupfont();
        MinecraftForge.EVENT_BUS.register((Object)this);
    }
    
    @Mod.EventHandler
    public void init(final FMLInitializationEvent event) {
        Main.LOGGER.info("Setup FutureX Version 0.0.1");
        Main.proxy.init(event);
        Main.Evtmgr = new EventsHandler();
        Main.Cevtmgr = new CustomEventsHandler();
        Main.Xray = new XrayGui();
        Main.Search = new SearchGui();
        Main.AntiPacketgui = new AntiPacketGui();
        Main.GuiEsp = new EspGui();
        Main.setmgr = new SettingsManager();
        new ModuleManager();
        new NewScreen();
        Main.OnscreenGUI = new OnscreenGUI();
        Main.ClickGui = new ClickGui();
    }
    
    @Mod.EventHandler
    public void postInit(final FMLPostInitializationEvent event) {
        Main.LOGGER.info("Final FutureX Version 0.0.1");
        new FileManager();
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.ClickGui);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.OnscreenGUI);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.Evtmgr);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.Cevtmgr);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.AntiPacketgui);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.GuiEsp);
        Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Main.Xray);
        if (CommandManager.getInstance() == null) {
            CommandManager.getInstance();
        }
        Display.setTitle("FutureX");
        ClientProxy.Gl = ModuleManager.getModuleByName("ArmorRender");
    }
    
    static {
        LOGGER = LogManager.getLogger();
    }
}
